### ISSUE TITLE
Eine Komponente pro Datei

### ISSUE THREAD

**Issue by Soean** [olrchhlm/ToDoApp-React#4]
Die Datei `List.js` enthält 2 Komponenten `List`  und `ListComponent`. In jeder Datei sollte nur eine Komponente sein, daher sollte `ListComponent` in eine eigene verschoben werden.

**Comment by Soean** [comment]
Bitte Ticket erst schließen, wenn es im Master ist ;-)

**Comment by olrchhlm** [comment]
Jetzt ists auch im Master :D
